CREATE DATABASE IF NOT EXISTS GameTracker;

USE GameTracker;

CREATE TABLE IF NOT EXISTS Developers (
	DeveloperID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	Name varchar(255),
	PRIMARY KEY(DeveloperID)
);

CREATE TABLE IF NOT EXISTS Games (
	GameID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	Name varchar(255),
	DeveloperID INTEGER UNSIGNED,
	AverageScore FLOAT,
	PRIMARY KEY(GameID),
	FOREIGN KEY(DeveloperID) REFERENCES Developers(DeveloperID)

);

CREATE TABLE IF NOT EXISTS Players (
	PlayerID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	Name varchar(255),
	Age INTEGER,
	PRIMARY KEY(PlayerID)
);


CREATE TABLE IF NOT EXISTS HasPlayed (
	PlayerID INTEGER UNSIGNED NOT NULL,
	GameID INTEGER UNSIGNED NOT NULL,
	Score INTEGER,
	DateFinished DATE,
	PRIMARY KEY(PlayerID, GameID),
    FOREIGN KEY(PlayerID) REFERENCES Players(PlayerID),
	FOREIGN KEY(GameID) REFERENCES Games(GameID)
);






